name: puzzle_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animated_text_kit: 4.2.1
  firebase_core: 1.12.0
  google_sign_in: 5.2.3
  firebase_auth: 3.3.6
  cloud_firestore: ^3.1.7
  firebase_storage: ^10.2.6
  responsive_layout_builder: 0.5.0
  animated: 2.0.0
  marquee: ^2.2.0
  lottie: ^1.2.1
  device_preview: ^1.0.0
  confetti: 0.6.0-nullsafety
  simple_animations: ^4.0.1
  flutter_sequence_animation: ^3.0.1
  equatable: ^2.0.3
  provider: ^6.0.2
  file_picker: 4.3.3
  image: ^3.0.1
  fluttertoast: ^8.0.9
  google_sign_in_web: 0.10.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.1+1

flutter_native_splash:
  color: "#4F69C6"
  image: assets/output-onlinepngtools.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ball.png
    - assets/rollingball/4.jpeg
    - assets/rollingball/Untitled.png
    - assets/rollingball2/Untitled.png
    - assets/33886-check-okey-done.json
    - assets/94539-order-history.gif
    - assets/7877-uploading-to-cloud.json
    - assets/7491-uploading-files.json
    - assets/9992-name-profile-icon-animation-filled.json
    - assets/94539-order-history.json
    - assets/25984-carousel-arrow-right.json
    - assets/animation_200_kzi33lyz.gif
    - assets/claw-machine.png
    - assets/animation_500_kznx9bxc.gif
    - assets/dash-facing-front.jpeg
    - assets/blue/1.png
    - assets/blue/2.png
    - assets/blue/3.png
    - assets/blue/4.png
    - assets/blue/5.png
    - assets/blue/6.png
    - assets/blue/7.png
    - assets/blue/8.png
    - assets/blue/9.png
    - assets/blue/10.png
    - assets/blue/11.png
    - assets/blue/12.png
    - assets/blue/13.png
    - assets/blue/14.png
    - assets/blue/15.png
    - assets/blue/blue.png
    - assets/blue/bluepuzzle.png
    - assets/green/1.png
    - assets/green/2.png
    - assets/green/3.png
    - assets/green/4.png
    - assets/green/5.png
    - assets/green/6.png
    - assets/green/7.png
    - assets/green/8.png
    - assets/green/9.png
    - assets/green/10.png
    - assets/green/11.png
    - assets/green/12.png
    - assets/green/13.png
    - assets/green/14.png
    - assets/green/15.png
    - assets/green/green.png
    - assets/green/greenpuzzle.png
    - assets/yellow/1.png
    - assets/yellow/2.png
    - assets/yellow/3.png
    - assets/yellow/4.png
    - assets/yellow/5.png
    - assets/yellow/6.png
    - assets/yellow/7.png
    - assets/yellow/8.png
    - assets/yellow/9.png
    - assets/yellow/10.png
    - assets/yellow/11.png
    - assets/yellow/12.png
    - assets/yellow/13.png
    - assets/yellow/14.png
    - assets/yellow/15.png
    - assets/yellow/yellow.png
    - assets/yellow/yellowpuzzle.png
    - assets/rollingball/1.png
    - assets/rollingball/2.png
    - assets/rollingball/3.png
    - assets/rollingball/4.png
    - assets/rollingball/5.png
    - assets/rollingball/6.png
    - assets/rollingball/7.png
    - assets/rollingball/8.png
    - assets/rollingball2/1.png
    - assets/rollingball2/2.png
    - assets/rollingball2/3.png
    - assets/rollingball2/4.jpeg
    - assets/rollingball2/4.png
    - assets/rollingball2/5.png
    - assets/rollingball2/6.png
    - assets/rollingball2/7.png
    - assets/rollingball2/8.png
    - assets/mathgame.png
    - assets/rollingball1.png
    - assets/rollingball2.png
    - assets/68582-log-out.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: TitanOne
     fonts:
       - asset: font/TitanOne-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
